# Generated by Django 5.1.6 on 2025-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description", models.TextField()),
                ("resume_file", models.FileField(upload_to="resumes/")),
                ("score", models.IntegerField()),
                ("keywords_missing", models.TextField(blank=True)),
                ("final_thoughts", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
