# Generated by Django 6.0 on 2025-12-29 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumerecord',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='resumerecord',
            name='final_thoughts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumerecord',
            name='keywords_missing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumerecord',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
